feat[flatpak-integrator]: add support for flatpak chromium variants
Adds support for Chrome & Chromium based flatpak
browsers.

diff --git a/flatpak-integrator/flatpak-host-wrapper b/flatpak-integrator/flatpak-host-wrapper
--- a/flatpak-integrator/flatpak-host-wrapper
+++ b/flatpak-integrator/flatpak-host-wrapper
@@ -7,8 +7,18 @@
 
 set -eu
 
-# This packs $1 and $2 into a single string for gdbus of the form "'$1', '$2'\n"
-args=$(printf "'%s', '%s'\n" "$1" "$2")
+# Format arguments for gdbus based on whether it's Firefox (2 args) or Chrome (1 arg)
+# See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#exchanging_messages
+if [ $# -eq 2 ]; then
+    # Firefox case - pack $1 and $2 into a single string
+    args=$(printf "'%s', '%s'\n" "$1" "$2")
+elif [ $# -eq 1 ]; then
+    # Chrome case - format single argument
+    args=$(printf "'%s'\n" "$1")
+else
+    echo "Error: Expected 1 (Chrome) or 2 (Firefox) arguments but got $#" >&2
+    exit 1
+fi
 
 # The descriptor madness needs some explaining:
 # We expect the forked gdbus to pick up three descriptors from us: 3, 4, and 5, respectively presenting our
